name: Gradle Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - uses: gradle/actions/setup-gradle@v4
    - name: Build
      run: ./gradlew build
    - name: Lint
      run: ./gradlew ktlintCheck
    - name: Test
      run: ./gradlew test